<?php

/**
 * Invoice
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-09-14, 02:07:10
 */
class Invoice extends \Phalcon\Mvc\Model {

// **********************
// ATTRIBUTE DECLARATION
// **********************

    protected $TxnID;
    protected $TimeCreated;
    protected $TimeModified;
    protected $EditSequence;
    protected $TxnNumber;
    protected $CustomerRef_ListID;
    protected $CustomerRef_FullName;
    protected $ClassRef_ListID;
    protected $ClassRef_FullName;
    protected $ARAccountRef_ListID;
    protected $ARAccountRef_FullName;
    protected $TemplateRef_ListID;
    protected $TemplateRef_FullName;
    protected $TxnDate;
    protected $RefNumber;
    protected $BillAddress_Addr1;
    protected $BillAddress_Addr2;
    protected $BillAddress_Addr3;
    protected $BillAddress_Addr4;
    protected $BillAddress_Addr5;
    protected $BillAddress_City;
    protected $BillAddress_State;
    protected $BillAddress_PostalCode;
    protected $BillAddress_Country;
    protected $BillAddress_Note;
    protected $ShipAddress_Addr1;
    protected $ShipAddress_Addr2;
    protected $ShipAddress_Addr3;
    protected $ShipAddress_Addr4;
    protected $ShipAddress_Addr5;
    protected $ShipAddress_City;
    protected $ShipAddress_State;
    protected $ShipAddress_PostalCode;
    protected $ShipAddress_Country;
    protected $ShipAddress_Note;
    protected $IsPending;
    protected $IsFinanceCharge;
    protected $PONumber;
    protected $TermsRef_ListID;
    protected $TermsRef_FullName;
    protected $DueDate;
    protected $SalesRepRef_ListID;
    protected $SalesRepRef_FullName;
    protected $FOB;
    protected $ShipDate;
    protected $ShipMethodRef_ListID;
    protected $ShipMethodRef_FullName;
    protected $Subtotal;
    protected $ItemSalesTaxRef_ListID;
    protected $ItemSalesTaxRef_FullName;
    protected $SalesTaxPercentage;
    protected $SalesTaxTotal;
    protected $AppliedAmount;
    protected $BalanceRemaining;
    protected $CurrencyRef_ListID;
    protected $CurrencyRef_FullName;
    protected $ExchangeRate;
    protected $BalanceRemainingInHomeCurrency;
    protected $Memo;
    protected $IsPaID;
    protected $CustomerMsgRef_ListID;
    protected $CustomerMsgRef_FullName;
    protected $IsToBePrinted;
    protected $IsToBeEmailed;
    protected $IsTaxIncluded;
    protected $CustomerSalesTaxCodeRef_ListID;
    protected $CustomerSalesTaxCodeRef_FullName;
    protected $SuggestedDiscountAmount;
    protected $SuggestedDiscountDate;
    protected $Other;
    protected $CustomField1;
    protected $CustomField2;
    protected $CustomField3;
    protected $CustomField4;
    protected $CustomField5;
    protected $CustomField6;
    protected $CustomField7;
    protected $CustomField8;
    protected $CustomField9;
    protected $CustomField10;
    protected $CustomField11;
    protected $CustomField12;
    protected $CustomField13;
    protected $CustomField14;
    protected $CustomField15;
    protected $Status;

    function onConstruct() {

        $fecha = date('Y-m-d H:m:s');
        $this->TxnID = ' ';
        $this->TimeCreated = $fecha;
        $this->TimeModified = $fecha;
        $this->EditSequence = rand(10000, 10000000);
        $this->TxnNumber = 0;
        $this->CustomerRef_ListID = ' ';
        $this->CustomerRef_FullName = ' ';
        $this->ClassRef_ListID = ' ';
        $this->ClassRef_FullName = ' ';
        $this->ARAccountRef_ListID = ' ';
        $this->ARAccountRef_FullName = ' ';
        $this->TemplateRef_ListID = ' ';
        $this->TemplateRef_FullName = ' ';
        $this->TxnDate = $fecha;
        $this->RefNumber = ' ';
        $this->BillAddress_Addr1 = ' ';
        $this->BillAddress_Addr2 = ' ';
        $this->BillAddress_Addr3 = ' ';
        $this->BillAddress_Addr4 = ' ';
        $this->BillAddress_Addr5 = ' ';
        $this->BillAddress_City = ' ';
        $this->BillAddress_State = ' ';
        $this->BillAddress_PostalCode = ' ';
        $this->BillAddress_Country = ' ';
        $this->BillAddress_Note = ' ';
        $this->ShipAddress_Addr1 = ' ';
        $this->ShipAddress_Addr2 = ' ';
        $this->ShipAddress_Addr3 = ' ';
        $this->ShipAddress_Addr4 = ' ';
        $this->ShipAddress_Addr5 = ' ';
        $this->ShipAddress_City = ' ';
        $this->ShipAddress_State = ' ';
        $this->ShipAddress_PostalCode = ' ';
        $this->ShipAddress_Country = ' ';
        $this->ShipAddress_Note = ' ';
        $this->IsPending = 'false';
        $this->IsFinanceCharge = 'false';
        $this->PONumber = ' ';
        $this->TermsRef_ListID = ' ';
        $this->TermsRef_FullName = ' ';
        $this->DueDate = $fecha;
        $this->SalesRepRef_ListID = ' ';
        $this->SalesRepRef_FullName = ' ';
        $this->FOB = ' ';
        $this->ShipDate = $fecha;
        $this->ShipMethodRef_ListID = ' ';
        $this->ShipMethodRef_FullName = ' ';
        $this->Subtotal = 0;
        $this->ItemSalesTaxRef_ListID = ' ';
        $this->ItemSalesTaxRef_FullName = ' ';
        $this->SalesTaxPercentage = 0;
        $this->SalesTaxTotal = 0;
        $this->AppliedAmount = 0;
        $this->BalanceRemaining = 0;
        $this->CurrencyRef_ListID = ' ';
        $this->CurrencyRef_FullName = ' ';
        $this->ExchangeRate = 0;
        $this->BalanceRemainingInHomeCurrency = 0;
        $this->Memo = ' ';
        $this->IsPaID = 'false';
        $this->CustomerMsgRef_ListID = ' ';
        $this->CustomerMsgRef_FullName = ' ';
        $this->IsToBePrinted = 'false';
        $this->IsToBeEmailed = 'false';
        $this->IsTaxIncluded = 'false';
        $this->CustomerSalesTaxCodeRef_ListID = ' ';
        $this->CustomerSalesTaxCodeRef_FullName = ' ';
        $this->SuggestedDiscountAmount = 0;
        $this->SuggestedDiscountDate = $fecha;
        $this->Other = ' ';
        $this->CustomField1 = 'n/a';
        $this->CustomField2 = 'n/a';
        $this->CustomField3 = 'n/a';
        $this->CustomField4 = 'n/a';
        $this->CustomField5 = 'n/a';
        $this->CustomField6 = 'n/a';
        $this->CustomField7 = 'n/a';
        $this->CustomField8 = 'n/a';
        $this->CustomField9 = 'n/a';
        $this->CustomField10 = 'n/a';
        $this->CustomField11 = 'n/a';
        $this->CustomField12 = 'n/a';
        $this->CustomField13 = 'n/a';
        $this->CustomField14 = 'n/a';
        $this->CustomField15 = 'n/a';
        $this->Status = 'ACTIVO';
    }

    /**
     * Method to set the value of field TxnID
     *
     * @param string $TxnID
     * @return $this
     */
    public function setTxnID($TxnID) {
        $this->TxnID = $TxnID;

        return $this;
    }

    /**
     * Method to set the value of field TimeCreated
     *
     * @param string $TimeCreated
     * @return $this
     */
    public function setTimeCreated($TimeCreated) {
        $this->TimeCreated = $TimeCreated;

        return $this;
    }

    /**
     * Method to set the value of field TimeModified
     *
     * @param string $TimeModified
     * @return $this
     */
    public function setTimeModified($TimeModified) {
        $this->TimeModified = $TimeModified;

        return $this;
    }

    /**
     * Method to set the value of field EditSequence
     *
     * @param string $EditSequence
     * @return $this
     */
    public function setEditSequence($EditSequence) {
        $this->EditSequence = $EditSequence;

        return $this;
    }

    /**
     * Method to set the value of field TxnNumber
     *
     * @param integer $TxnNumber
     * @return $this
     */
    public function setTxnNumber($TxnNumber) {
        $this->TxnNumber = $TxnNumber;

        return $this;
    }

    /**
     * Method to set the value of field CustomerRef_ListID
     *
     * @param string $CustomerRef_ListID
     * @return $this
     */
    public function setCustomerRefListID($CustomerRef_ListID) {
        $this->CustomerRef_ListID = $CustomerRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field CustomerRef_FullName
     *
     * @param string $CustomerRef_FullName
     * @return $this
     */
    public function setCustomerRefFullName($CustomerRef_FullName) {
        $this->CustomerRef_FullName = $CustomerRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field ClassRef_ListID
     *
     * @param string $ClassRef_ListID
     * @return $this
     */
    public function setClassRefListID($ClassRef_ListID) {
        $this->ClassRef_ListID = $ClassRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field ClassRef_FullName
     *
     * @param string $ClassRef_FullName
     * @return $this
     */
    public function setClassRefFullName($ClassRef_FullName) {
        $this->ClassRef_FullName = $ClassRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field ARAccountRef_ListID
     *
     * @param string $ARAccountRef_ListID
     * @return $this
     */
    public function setARAccountRefListID($ARAccountRef_ListID) {
        $this->ARAccountRef_ListID = $ARAccountRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field ARAccountRef_FullName
     *
     * @param string $ARAccountRef_FullName
     * @return $this
     */
    public function setARAccountRefFullName($ARAccountRef_FullName) {
        $this->ARAccountRef_FullName = $ARAccountRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field TemplateRef_ListID
     *
     * @param string $TemplateRef_ListID
     * @return $this
     */
    public function setTemplateRefListID($TemplateRef_ListID) {
        $this->TemplateRef_ListID = $TemplateRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field TemplateRef_FullName
     *
     * @param string $TemplateRef_FullName
     * @return $this
     */
    public function setTemplateRefFullName($TemplateRef_FullName) {
        $this->TemplateRef_FullName = $TemplateRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field TxnDate
     *
     * @param string $TxnDate
     * @return $this
     */
    public function setTxnDate($TxnDate) {
        $this->TxnDate = $TxnDate;

        return $this;
    }

    /**
     * Method to set the value of field RefNumber
     *
     * @param string $RefNumber
     * @return $this
     */
    public function setRefNumber($RefNumber) {
        $this->RefNumber = $RefNumber;

        return $this;
    }

    /**
     * Method to set the value of field BillAddress_Addr1
     *
     * @param string $BillAddress_Addr1
     * @return $this
     */
    public function setBillAddressAddr1($BillAddress_Addr1) {
        $this->BillAddress_Addr1 = $BillAddress_Addr1;

        return $this;
    }

    /**
     * Method to set the value of field BillAddress_Addr2
     *
     * @param string $BillAddress_Addr2
     * @return $this
     */
    public function setBillAddressAddr2($BillAddress_Addr2) {
        $this->BillAddress_Addr2 = $BillAddress_Addr2;

        return $this;
    }

    /**
     * Method to set the value of field BillAddress_Addr3
     *
     * @param string $BillAddress_Addr3
     * @return $this
     */
    public function setBillAddressAddr3($BillAddress_Addr3) {
        $this->BillAddress_Addr3 = $BillAddress_Addr3;

        return $this;
    }

    /**
     * Method to set the value of field BillAddress_Addr4
     *
     * @param string $BillAddress_Addr4
     * @return $this
     */
    public function setBillAddressAddr4($BillAddress_Addr4) {
        $this->BillAddress_Addr4 = $BillAddress_Addr4;

        return $this;
    }

    /**
     * Method to set the value of field BillAddress_Addr5
     *
     * @param string $BillAddress_Addr5
     * @return $this
     */
    public function setBillAddressAddr5($BillAddress_Addr5) {
        $this->BillAddress_Addr5 = $BillAddress_Addr5;

        return $this;
    }

    /**
     * Method to set the value of field BillAddress_City
     *
     * @param string $BillAddress_City
     * @return $this
     */
    public function setBillAddressCity($BillAddress_City) {
        $this->BillAddress_City = $BillAddress_City;

        return $this;
    }

    /**
     * Method to set the value of field BillAddress_State
     *
     * @param string $BillAddress_State
     * @return $this
     */
    public function setBillAddressState($BillAddress_State) {
        $this->BillAddress_State = $BillAddress_State;

        return $this;
    }

    /**
     * Method to set the value of field BillAddress_PostalCode
     *
     * @param string $BillAddress_PostalCode
     * @return $this
     */
    public function setBillAddressPostalCode($BillAddress_PostalCode) {
        $this->BillAddress_PostalCode = $BillAddress_PostalCode;

        return $this;
    }

    /**
     * Method to set the value of field BillAddress_Country
     *
     * @param string $BillAddress_Country
     * @return $this
     */
    public function setBillAddressCountry($BillAddress_Country) {
        $this->BillAddress_Country = $BillAddress_Country;

        return $this;
    }

    /**
     * Method to set the value of field BillAddress_Note
     *
     * @param string $BillAddress_Note
     * @return $this
     */
    public function setBillAddressNote($BillAddress_Note) {
        $this->BillAddress_Note = $BillAddress_Note;

        return $this;
    }

    /**
     * Method to set the value of field ShipAddress_Addr1
     *
     * @param string $ShipAddress_Addr1
     * @return $this
     */
    public function setShipAddressAddr1($ShipAddress_Addr1) {
        $this->ShipAddress_Addr1 = $ShipAddress_Addr1;

        return $this;
    }

    /**
     * Method to set the value of field ShipAddress_Addr2
     *
     * @param string $ShipAddress_Addr2
     * @return $this
     */
    public function setShipAddressAddr2($ShipAddress_Addr2) {
        $this->ShipAddress_Addr2 = $ShipAddress_Addr2;

        return $this;
    }

    /**
     * Method to set the value of field ShipAddress_Addr3
     *
     * @param string $ShipAddress_Addr3
     * @return $this
     */
    public function setShipAddressAddr3($ShipAddress_Addr3) {
        $this->ShipAddress_Addr3 = $ShipAddress_Addr3;

        return $this;
    }

    /**
     * Method to set the value of field ShipAddress_Addr4
     *
     * @param string $ShipAddress_Addr4
     * @return $this
     */
    public function setShipAddressAddr4($ShipAddress_Addr4) {
        $this->ShipAddress_Addr4 = $ShipAddress_Addr4;

        return $this;
    }

    /**
     * Method to set the value of field ShipAddress_Addr5
     *
     * @param string $ShipAddress_Addr5
     * @return $this
     */
    public function setShipAddressAddr5($ShipAddress_Addr5) {
        $this->ShipAddress_Addr5 = $ShipAddress_Addr5;

        return $this;
    }

    /**
     * Method to set the value of field ShipAddress_City
     *
     * @param string $ShipAddress_City
     * @return $this
     */
    public function setShipAddressCity($ShipAddress_City) {
        $this->ShipAddress_City = $ShipAddress_City;

        return $this;
    }

    /**
     * Method to set the value of field ShipAddress_State
     *
     * @param string $ShipAddress_State
     * @return $this
     */
    public function setShipAddressState($ShipAddress_State) {
        $this->ShipAddress_State = $ShipAddress_State;

        return $this;
    }

    /**
     * Method to set the value of field ShipAddress_PostalCode
     *
     * @param string $ShipAddress_PostalCode
     * @return $this
     */
    public function setShipAddressPostalCode($ShipAddress_PostalCode) {
        $this->ShipAddress_PostalCode = $ShipAddress_PostalCode;

        return $this;
    }

    /**
     * Method to set the value of field ShipAddress_Country
     *
     * @param string $ShipAddress_Country
     * @return $this
     */
    public function setShipAddressCountry($ShipAddress_Country) {
        $this->ShipAddress_Country = $ShipAddress_Country;

        return $this;
    }

    /**
     * Method to set the value of field ShipAddress_Note
     *
     * @param string $ShipAddress_Note
     * @return $this
     */
    public function setShipAddressNote($ShipAddress_Note) {
        $this->ShipAddress_Note = $ShipAddress_Note;

        return $this;
    }

    /**
     * Method to set the value of field IsPending
     *
     * @param string $IsPending
     * @return $this
     */
    public function setIsPending($IsPending) {
        $this->IsPending = $IsPending;

        return $this;
    }

    /**
     * Method to set the value of field IsFinanceCharge
     *
     * @param string $IsFinanceCharge
     * @return $this
     */
    public function setIsFinanceCharge($IsFinanceCharge) {
        $this->IsFinanceCharge = $IsFinanceCharge;

        return $this;
    }

    /**
     * Method to set the value of field PONumber
     *
     * @param string $PONumber
     * @return $this
     */
    public function setPONumber($PONumber) {
        $this->PONumber = $PONumber;

        return $this;
    }

    /**
     * Method to set the value of field TermsRef_ListID
     *
     * @param string $TermsRef_ListID
     * @return $this
     */
    public function setTermsRefListID($TermsRef_ListID) {
        $this->TermsRef_ListID = $TermsRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field TermsRef_FullName
     *
     * @param string $TermsRef_FullName
     * @return $this
     */
    public function setTermsRefFullName($TermsRef_FullName) {
        $this->TermsRef_FullName = $TermsRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field DueDate
     *
     * @param string $DueDate
     * @return $this
     */
    public function setDueDate($DueDate) {
        $this->DueDate = $DueDate;

        return $this;
    }

    /**
     * Method to set the value of field SalesRepRef_ListID
     *
     * @param string $SalesRepRef_ListID
     * @return $this
     */
    public function setSalesRepRefListID($SalesRepRef_ListID) {
        $this->SalesRepRef_ListID = $SalesRepRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field SalesRepRef_FullName
     *
     * @param string $SalesRepRef_FullName
     * @return $this
     */
    public function setSalesRepRefFullName($SalesRepRef_FullName) {
        $this->SalesRepRef_FullName = $SalesRepRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field FOB
     *
     * @param string $FOB
     * @return $this
     */
    public function setFOB($FOB) {
        $this->FOB = $FOB;

        return $this;
    }

    /**
     * Method to set the value of field ShipDate
     *
     * @param string $ShipDate
     * @return $this
     */
    public function setShipDate($ShipDate) {
        $this->ShipDate = $ShipDate;

        return $this;
    }

    /**
     * Method to set the value of field ShipMethodRef_ListID
     *
     * @param string $ShipMethodRef_ListID
     * @return $this
     */
    public function setShipMethodRefListID($ShipMethodRef_ListID) {
        $this->ShipMethodRef_ListID = $ShipMethodRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field ShipMethodRef_FullName
     *
     * @param string $ShipMethodRef_FullName
     * @return $this
     */
    public function setShipMethodRefFullName($ShipMethodRef_FullName) {
        $this->ShipMethodRef_FullName = $ShipMethodRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field Subtotal
     *
     * @param double $Subtotal
     * @return $this
     */
    public function setSubtotal($Subtotal) {
        $this->Subtotal = $Subtotal;

        return $this;
    }

    /**
     * Method to set the value of field ItemSalesTaxRef_ListID
     *
     * @param string $ItemSalesTaxRef_ListID
     * @return $this
     */
    public function setItemSalesTaxRefListID($ItemSalesTaxRef_ListID) {
        $this->ItemSalesTaxRef_ListID = $ItemSalesTaxRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field ItemSalesTaxRef_FullName
     *
     * @param string $ItemSalesTaxRef_FullName
     * @return $this
     */
    public function setItemSalesTaxRefFullName($ItemSalesTaxRef_FullName) {
        $this->ItemSalesTaxRef_FullName = $ItemSalesTaxRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field SalesTaxPercentage
     *
     * @param string $SalesTaxPercentage
     * @return $this
     */
    public function setSalesTaxPercentage($SalesTaxPercentage) {
        $this->SalesTaxPercentage = $SalesTaxPercentage;

        return $this;
    }

    /**
     * Method to set the value of field SalesTaxTotal
     *
     * @param double $SalesTaxTotal
     * @return $this
     */
    public function setSalesTaxTotal($SalesTaxTotal) {
        $this->SalesTaxTotal = $SalesTaxTotal;

        return $this;
    }

    /**
     * Method to set the value of field AppliedAmount
     *
     * @param double $AppliedAmount
     * @return $this
     */
    public function setAppliedAmount($AppliedAmount) {
        $this->AppliedAmount = $AppliedAmount;

        return $this;
    }

    /**
     * Method to set the value of field BalanceRemaining
     *
     * @param double $BalanceRemaining
     * @return $this
     */
    public function setBalanceRemaining($BalanceRemaining) {
        $this->BalanceRemaining = $BalanceRemaining;

        return $this;
    }

    /**
     * Method to set the value of field CurrencyRef_ListID
     *
     * @param string $CurrencyRef_ListID
     * @return $this
     */
    public function setCurrencyRefListID($CurrencyRef_ListID) {
        $this->CurrencyRef_ListID = $CurrencyRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field CurrencyRef_FullName
     *
     * @param string $CurrencyRef_FullName
     * @return $this
     */
    public function setCurrencyRefFullName($CurrencyRef_FullName) {
        $this->CurrencyRef_FullName = $CurrencyRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field ExchangeRate
     *
     * @param double $ExchangeRate
     * @return $this
     */
    public function setExchangeRate($ExchangeRate) {
        $this->ExchangeRate = $ExchangeRate;

        return $this;
    }

    /**
     * Method to set the value of field BalanceRemainingInHomeCurrency
     *
     * @param double $BalanceRemainingInHomeCurrency
     * @return $this
     */
    public function setBalanceRemainingInHomeCurrency($BalanceRemainingInHomeCurrency) {
        $this->BalanceRemainingInHomeCurrency = $BalanceRemainingInHomeCurrency;

        return $this;
    }

    /**
     * Method to set the value of field Memo
     *
     * @param string $Memo
     * @return $this
     */
    public function setMemo($Memo) {
        $this->Memo = $Memo;

        return $this;
    }

    /**
     * Method to set the value of field IsPaid
     *
     * @param string $IsPaid
     * @return $this
     */
    public function setIsPaid($IsPaid) {
        $this->IsPaid = $IsPaid;

        return $this;
    }

    /**
     * Method to set the value of field CustomerMsgRef_ListID
     *
     * @param string $CustomerMsgRef_ListID
     * @return $this
     */
    public function setCustomerMsgRefListID($CustomerMsgRef_ListID) {
        $this->CustomerMsgRef_ListID = $CustomerMsgRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field CustomerMsgRef_FullName
     *
     * @param string $CustomerMsgRef_FullName
     * @return $this
     */
    public function setCustomerMsgRefFullName($CustomerMsgRef_FullName) {
        $this->CustomerMsgRef_FullName = $CustomerMsgRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field IsToBePrinted
     *
     * @param string $IsToBePrinted
     * @return $this
     */
    public function setIsToBePrinted($IsToBePrinted) {
        $this->IsToBePrinted = $IsToBePrinted;

        return $this;
    }

    /**
     * Method to set the value of field IsToBeEmailed
     *
     * @param string $IsToBeEmailed
     * @return $this
     */
    public function setIsToBeEmailed($IsToBeEmailed) {
        $this->IsToBeEmailed = $IsToBeEmailed;

        return $this;
    }

    /**
     * Method to set the value of field IsTaxIncluded
     *
     * @param string $IsTaxIncluded
     * @return $this
     */
    public function setIsTaxIncluded($IsTaxIncluded) {
        $this->IsTaxIncluded = $IsTaxIncluded;

        return $this;
    }

    /**
     * Method to set the value of field CustomerSalesTaxCodeRef_ListID
     *
     * @param string $CustomerSalesTaxCodeRef_ListID
     * @return $this
     */
    public function setCustomerSalesTaxCodeRefListID($CustomerSalesTaxCodeRef_ListID) {
        $this->CustomerSalesTaxCodeRef_ListID = $CustomerSalesTaxCodeRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field CustomerSalesTaxCodeRef_FullName
     *
     * @param string $CustomerSalesTaxCodeRef_FullName
     * @return $this
     */
    public function setCustomerSalesTaxCodeRefFullName($CustomerSalesTaxCodeRef_FullName) {
        $this->CustomerSalesTaxCodeRef_FullName = $CustomerSalesTaxCodeRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field SuggestedDiscountAmount
     *
     * @param double $SuggestedDiscountAmount
     * @return $this
     */
    public function setSuggestedDiscountAmount($SuggestedDiscountAmount) {
        $this->SuggestedDiscountAmount = $SuggestedDiscountAmount;

        return $this;
    }

    /**
     * Method to set the value of field SuggestedDiscountDate
     *
     * @param string $SuggestedDiscountDate
     * @return $this
     */
    public function setSuggestedDiscountDate($SuggestedDiscountDate) {
        $this->SuggestedDiscountDate = $SuggestedDiscountDate;

        return $this;
    }

    /**
     * Method to set the value of field Other
     *
     * @param string $Other
     * @return $this
     */
    public function setOther($Other) {
        $this->Other = $Other;

        return $this;
    }

    /**
     * Method to set the value of field CustomField1
     *
     * @param string $CustomField1
     * @return $this
     */
    public function setCustomField1($CustomField1) {
        $this->CustomField1 = $CustomField1;

        return $this;
    }

    /**
     * Method to set the value of field CustomField2
     *
     * @param string $CustomField2
     * @return $this
     */
    public function setCustomField2($CustomField2) {
        $this->CustomField2 = $CustomField2;

        return $this;
    }

    /**
     * Method to set the value of field CustomField3
     *
     * @param string $CustomField3
     * @return $this
     */
    public function setCustomField3($CustomField3) {
        $this->CustomField3 = $CustomField3;

        return $this;
    }

    /**
     * Method to set the value of field CustomField4
     *
     * @param string $CustomField4
     * @return $this
     */
    public function setCustomField4($CustomField4) {
        $this->CustomField4 = $CustomField4;

        return $this;
    }

    /**
     * Method to set the value of field CustomField5
     *
     * @param string $CustomField5
     * @return $this
     */
    public function setCustomField5($CustomField5) {
        $this->CustomField5 = $CustomField5;

        return $this;
    }

    /**
     * Method to set the value of field CustomField6
     *
     * @param string $CustomField6
     * @return $this
     */
    public function setCustomField6($CustomField6) {
        $this->CustomField6 = $CustomField6;

        return $this;
    }

    /**
     * Method to set the value of field CustomField7
     *
     * @param string $CustomField7
     * @return $this
     */
    public function setCustomField7($CustomField7) {
        $this->CustomField7 = $CustomField7;

        return $this;
    }

    /**
     * Method to set the value of field CustomField8
     *
     * @param string $CustomField8
     * @return $this
     */
    public function setCustomField8($CustomField8) {
        $this->CustomField8 = $CustomField8;

        return $this;
    }

    /**
     * Method to set the value of field CustomField9
     *
     * @param string $CustomField9
     * @return $this
     */
    public function setCustomField9($CustomField9) {
        $this->CustomField9 = $CustomField9;

        return $this;
    }

    /**
     * Method to set the value of field CustomField10
     *
     * @param string $CustomField10
     * @return $this
     */
    public function setCustomField10($CustomField10) {
        $this->CustomField10 = $CustomField10;

        return $this;
    }

    /**
     * Method to set the value of field CustomField11
     *
     * @param string $CustomField11
     * @return $this
     */
    public function setCustomField11($CustomField11) {
        $this->CustomField11 = $CustomField11;

        return $this;
    }

    /**
     * Method to set the value of field CustomField12
     *
     * @param string $CustomField12
     * @return $this
     */
    public function setCustomField12($CustomField12) {
        $this->CustomField12 = $CustomField12;

        return $this;
    }

    /**
     * Method to set the value of field CustomField13
     *
     * @param string $CustomField13
     * @return $this
     */
    public function setCustomField13($CustomField13) {
        $this->CustomField13 = $CustomField13;

        return $this;
    }

    /**
     * Method to set the value of field CustomField14
     *
     * @param string $CustomField14
     * @return $this
     */
    public function setCustomField14($CustomField14) {
        $this->CustomField14 = $CustomField14;

        return $this;
    }

    /**
     * Method to set the value of field CustomField15
     *
     * @param string $CustomField15
     * @return $this
     */
    public function setCustomField15($CustomField15) {
        $this->CustomField15 = $CustomField15;

        return $this;
    }

    /**
     * Method to set the value of field Status
     *
     * @param string $Status
     * @return $this
     */
    public function setStatus($Status) {
        $this->Status = $Status;

        return $this;
    }

    /**
     * Returns the value of field TxnID
     *
     * @return string
     */
    public function getTxnID() {
        return $this->TxnID;
    }

    /**
     * Returns the value of field TimeCreated
     *
     * @return string
     */
    public function getTimeCreated() {
        return $this->TimeCreated;
    }

    /**
     * Returns the value of field TimeModified
     *
     * @return string
     */
    public function getTimeModified() {
        return $this->TimeModified;
    }

    /**
     * Returns the value of field EditSequence
     *
     * @return string
     */
    public function getEditSequence() {
        return $this->EditSequence;
    }

    /**
     * Returns the value of field TxnNumber
     *
     * @return integer
     */
    public function getTxnNumber() {
        return $this->TxnNumber;
    }

    /**
     * Returns the value of field CustomerRef_ListID
     *
     * @return string
     */
    public function getCustomerRefListID() {
        return $this->CustomerRef_ListID;
    }

    /**
     * Returns the value of field CustomerRef_FullName
     *
     * @return string
     */
    public function getCustomerRefFullName() {
        return $this->CustomerRef_FullName;
    }

    /**
     * Returns the value of field ClassRef_ListID
     *
     * @return string
     */
    public function getClassRefListID() {
        return $this->ClassRef_ListID;
    }

    /**
     * Returns the value of field ClassRef_FullName
     *
     * @return string
     */
    public function getClassRefFullName() {
        return $this->ClassRef_FullName;
    }

    /**
     * Returns the value of field ARAccountRef_ListID
     *
     * @return string
     */
    public function getARAccountRefListID() {
        return $this->ARAccountRef_ListID;
    }

    /**
     * Returns the value of field ARAccountRef_FullName
     *
     * @return string
     */
    public function getARAccountRefFullName() {
        return $this->ARAccountRef_FullName;
    }

    /**
     * Returns the value of field TemplateRef_ListID
     *
     * @return string
     */
    public function getTemplateRefListID() {
        return $this->TemplateRef_ListID;
    }

    /**
     * Returns the value of field TemplateRef_FullName
     *
     * @return string
     */
    public function getTemplateRefFullName() {
        return $this->TemplateRef_FullName;
    }

    /**
     * Returns the value of field TxnDate
     *
     * @return string
     */
    public function getTxnDate() {
        $val = date('F j, Y', strtotime($this->TxnDate));
        return $val;
//        return $this->TxnDate;
    }

    /**
     * Returns the value of field RefNumber
     *
     * @return string
     */
    public function getRefNumber() {
        return $this->RefNumber;
    }

    /**
     * Returns the value of field BillAddress_Addr1
     *
     * @return string
     */
    public function getBillAddressAddr1() {
        return $this->BillAddress_Addr1;
    }

    /**
     * Returns the value of field BillAddress_Addr2
     *
     * @return string
     */
    public function getBillAddressAddr2() {
        return $this->BillAddress_Addr2;
    }

    /**
     * Returns the value of field BillAddress_Addr3
     *
     * @return string
     */
    public function getBillAddressAddr3() {
        return $this->BillAddress_Addr3;
    }

    /**
     * Returns the value of field BillAddress_Addr4
     *
     * @return string
     */
    public function getBillAddressAddr4() {
        return $this->BillAddress_Addr4;
    }

    /**
     * Returns the value of field BillAddress_Addr5
     *
     * @return string
     */
    public function getBillAddressAddr5() {
        return $this->BillAddress_Addr5;
    }

    /**
     * Returns the value of field BillAddress_City
     *
     * @return string
     */
    public function getBillAddressCity() {
        return $this->BillAddress_City;
    }

    /**
     * Returns the value of field BillAddress_State
     *
     * @return string
     */
    public function getBillAddressState() {
        return $this->BillAddress_State;
    }

    /**
     * Returns the value of field BillAddress_PostalCode
     *
     * @return string
     */
    public function getBillAddressPostalCode() {
        return $this->BillAddress_PostalCode;
    }

    /**
     * Returns the value of field BillAddress_Country
     *
     * @return string
     */
    public function getBillAddressCountry() {
        return $this->BillAddress_Country;
    }

    /**
     * Returns the value of field BillAddress_Note
     *
     * @return string
     */
    public function getBillAddressNote() {
        return $this->BillAddress_Note;
    }

    /**
     * Returns the value of field ShipAddress_Addr1
     *
     * @return string
     */
    public function getShipAddressAddr1() {
        return $this->ShipAddress_Addr1;
    }

    /**
     * Returns the value of field ShipAddress_Addr2
     *
     * @return string
     */
    public function getShipAddressAddr2() {
        return $this->ShipAddress_Addr2;
    }

    /**
     * Returns the value of field ShipAddress_Addr3
     *
     * @return string
     */
    public function getShipAddressAddr3() {
        return $this->ShipAddress_Addr3;
    }

    /**
     * Returns the value of field ShipAddress_Addr4
     *
     * @return string
     */
    public function getShipAddressAddr4() {
        return $this->ShipAddress_Addr4;
    }

    /**
     * Returns the value of field ShipAddress_Addr5
     *
     * @return string
     */
    public function getShipAddressAddr5() {
        return $this->ShipAddress_Addr5;
    }

    /**
     * Returns the value of field ShipAddress_City
     *
     * @return string
     */
    public function getShipAddressCity() {
        return $this->ShipAddress_City;
    }

    /**
     * Returns the value of field ShipAddress_State
     *
     * @return string
     */
    public function getShipAddressState() {
        return $this->ShipAddress_State;
    }

    /**
     * Returns the value of field ShipAddress_PostalCode
     *
     * @return string
     */
    public function getShipAddressPostalCode() {
        return $this->ShipAddress_PostalCode;
    }

    /**
     * Returns the value of field ShipAddress_Country
     *
     * @return string
     */
    public function getShipAddressCountry() {
        return $this->ShipAddress_Country;
    }

    /**
     * Returns the value of field ShipAddress_Note
     *
     * @return string
     */
    public function getShipAddressNote() {
        return $this->ShipAddress_Note;
    }

    /**
     * Returns the value of field IsPending
     *
     * @return string
     */
    public function getIsPending() {
        return $this->IsPending;
    }

    /**
     * Returns the value of field IsFinanceCharge
     *
     * @return string
     */
    public function getIsFinanceCharge() {
        return $this->IsFinanceCharge;
    }

    /**
     * Returns the value of field PONumber
     *
     * @return string
     */
    public function getPONumber() {
        return $this->PONumber;
    }

    /**
     * Returns the value of field TermsRef_ListID
     *
     * @return string
     */
    public function getTermsRefListID() {
        return $this->TermsRef_ListID;
    }

    /**
     * Returns the value of field TermsRef_FullName
     *
     * @return string
     */
    public function getTermsRefFullName() {
        return $this->TermsRef_FullName;
    }

    /**
     * Returns the value of field DueDate
     *
     * @return string
     */
    public function getDueDate() {
        return $this->DueDate;
    }

    /**
     * Returns the value of field SalesRepRef_ListID
     *
     * @return string
     */
    public function getSalesRepRefListID() {
        return $this->SalesRepRef_ListID;
    }

    /**
     * Returns the value of field SalesRepRef_FullName
     *
     * @return string
     */
    public function getSalesRepRefFullName() {
        return $this->SalesRepRef_FullName;
    }

    /**
     * Returns the value of field FOB
     *
     * @return string
     */
    public function getFOB() {
        return $this->FOB;
    }

    /**
     * Returns the value of field ShipDate
     *
     * @return string
     */
    public function getShipDate() {
        return $this->ShipDate;
    }

    /**
     * Returns the value of field ShipMethodRef_ListID
     *
     * @return string
     */
    public function getShipMethodRefListID() {
        return $this->ShipMethodRef_ListID;
    }

    /**
     * Returns the value of field ShipMethodRef_FullName
     *
     * @return string
     */
    public function getShipMethodRefFullName() {
        return $this->ShipMethodRef_FullName;
    }

    /**
     * Returns the value of field Subtotal
     *
     * @return double
     */
    public function getSubtotal() {
        return $this->Subtotal;
    }

    /**
     * Returns the value of field ItemSalesTaxRef_ListID
     *
     * @return string
     */
    public function getItemSalesTaxRefListID() {
        return $this->ItemSalesTaxRef_ListID;
    }

    /**
     * Returns the value of field ItemSalesTaxRef_FullName
     *
     * @return string
     */
    public function getItemSalesTaxRefFullName() {
        return $this->ItemSalesTaxRef_FullName;
    }

    /**
     * Returns the value of field SalesTaxPercentage
     *
     * @return string
     */
    public function getSalesTaxPercentage() {
        return $this->SalesTaxPercentage;
    }

    /**
     * Returns the value of field SalesTaxTotal
     *
     * @return double
     */
    public function getSalesTaxTotal() {
        return $this->SalesTaxTotal;
    }

    /**
     * Returns the value of field AppliedAmount
     *
     * @return double
     */
    public function getAppliedAmount() {
        return $this->AppliedAmount;
    }

    /**
     * Returns the value of field BalanceRemaining
     *
     * @return double
     */
    public function getBalanceRemaining() {
        return $this->BalanceRemaining;
    }

    /**
     * Returns the value of field CurrencyRef_ListID
     *
     * @return string
     */
    public function getCurrencyRefListID() {
        return $this->CurrencyRef_ListID;
    }

    /**
     * Returns the value of field CurrencyRef_FullName
     *
     * @return string
     */
    public function getCurrencyRefFullName() {
        return $this->CurrencyRef_FullName;
    }

    /**
     * Returns the value of field ExchangeRate
     *
     * @return double
     */
    public function getExchangeRate() {
        return $this->ExchangeRate;
    }

    /**
     * Returns the value of field BalanceRemainingInHomeCurrency
     *
     * @return double
     */
    public function getBalanceRemainingInHomeCurrency() {
        return $this->BalanceRemainingInHomeCurrency;
    }

    /**
     * Returns the value of field Memo
     *
     * @return string
     */
    public function getMemo() {
        return $this->Memo;
    }

    /**
     * Returns the value of field IsPaid
     *
     * @return string
     */
    public function getIsPaid() {
        return $this->IsPaid;
    }

    /**
     * Returns the value of field CustomerMsgRef_ListID
     *
     * @return string
     */
    public function getCustomerMsgRefListID() {
        return $this->CustomerMsgRef_ListID;
    }

    /**
     * Returns the value of field CustomerMsgRef_FullName
     *
     * @return string
     */
    public function getCustomerMsgRefFullName() {
        return $this->CustomerMsgRef_FullName;
    }

    /**
     * Returns the value of field IsToBePrinted
     *
     * @return string
     */
    public function getIsToBePrinted() {
        return $this->IsToBePrinted;
    }

    /**
     * Returns the value of field IsToBeEmailed
     *
     * @return string
     */
    public function getIsToBeEmailed() {
        return $this->IsToBeEmailed;
    }

    /**
     * Returns the value of field IsTaxIncluded
     *
     * @return string
     */
    public function getIsTaxIncluded() {
        return $this->IsTaxIncluded;
    }

    /**
     * Returns the value of field CustomerSalesTaxCodeRef_ListID
     *
     * @return string
     */
    public function getCustomerSalesTaxCodeRefListID() {
        return $this->CustomerSalesTaxCodeRef_ListID;
    }

    /**
     * Returns the value of field CustomerSalesTaxCodeRef_FullName
     *
     * @return string
     */
    public function getCustomerSalesTaxCodeRefFullName() {
        return $this->CustomerSalesTaxCodeRef_FullName;
    }

    /**
     * Returns the value of field SuggestedDiscountAmount
     *
     * @return double
     */
    public function getSuggestedDiscountAmount() {
        return $this->SuggestedDiscountAmount;
    }

    /**
     * Returns the value of field SuggestedDiscountDate
     *
     * @return string
     */
    public function getSuggestedDiscountDate() {
        return $this->SuggestedDiscountDate;
    }

    /**
     * Returns the value of field Other
     *
     * @return string
     */
    public function getOther() {
        return $this->Other;
    }

    /**
     * Returns the value of field CustomField1
     *
     * @return string
     */
    public function getCustomField1() {
        return $this->CustomField1;
    }

    /**
     * Returns the value of field CustomField2
     *
     * @return string
     */
    public function getCustomField2() {
        return $this->CustomField2;
    }

    /**
     * Returns the value of field CustomField3
     *
     * @return string
     */
    public function getCustomField3() {
        return $this->CustomField3;
    }

    /**
     * Returns the value of field CustomField4
     *
     * @return string
     */
    public function getCustomField4() {
        return $this->CustomField4;
    }

    /**
     * Returns the value of field CustomField5
     *
     * @return string
     */
    public function getCustomField5() {
        return $this->CustomField5;
    }

    /**
     * Returns the value of field CustomField6
     *
     * @return string
     */
    public function getCustomField6() {
        return $this->CustomField6;
    }

    /**
     * Returns the value of field CustomField7
     *
     * @return string
     */
    public function getCustomField7() {
        return $this->CustomField7;
    }

    /**
     * Returns the value of field CustomField8
     *
     * @return string
     */
    public function getCustomField8() {
        return $this->CustomField8;
    }

    /**
     * Returns the value of field CustomField9
     *
     * @return string
     */
    public function getCustomField9() {
        return $this->CustomField9;
    }

    /**
     * Returns the value of field CustomField10
     *
     * @return string
     */
    public function getCustomField10() {
        return $this->CustomField10;
    }

    /**
     * Returns the value of field CustomField11
     *
     * @return string
     */
    public function getCustomField11() {
        return $this->CustomField11;
    }

    /**
     * Returns the value of field CustomField12
     *
     * @return string
     */
    public function getCustomField12() {
        return $this->CustomField12;
    }

    /**
     * Returns the value of field CustomField13
     *
     * @return string
     */
    public function getCustomField13() {
        return $this->CustomField13;
    }

    /**
     * Returns the value of field CustomField14
     *
     * @return string
     */
    public function getCustomField14() {
        return $this->CustomField14;
    }

    /**
     * Returns the value of field CustomField15
     *
     * @return string
     */
    public function getCustomField15() {
        return $this->CustomField15;
    }

    /**
     * Returns the value of field Status
     *
     * @return string
     */
    public function getStatus() {
        return $this->Status;
    }

    /**
     * Initialize method for model.
     */
    public function initialize() {
        $this->setSchema("mecanica");
        $this->hasMany(
                'TxnID', 'Invoicelinedetail', 'IDKEY'
        );
        $this->belongsTo(
                'CustomerRef_ListID', 'Customer', 'ListID'
        );
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource() {
        return 'invoice';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Invoice[]|Invoice
     */
    public static function find($parameters = null) {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Invoice
     */
    public static function findFirst($parameters = null) {
        return parent::findFirst($parameters);
    }

}
