<?php

/**
 * Invoicelinedetail
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-09-14, 02:11:11
 */
class Invoicelinedetail extends \Phalcon\Mvc\Model {

// **********************
// ATTRIBUTE DECLARATION
// **********************

    protected $TxnLineID;
    protected $ItemRef_ListID;
    protected $ItemRef_FullName;
    protected $Description;
    protected $Quantity;
    protected $UnitOfMeasure;
    protected $OverrideUOMSetRef_ListID;
    protected $OverrideUOMSetRef_FullName;
    protected $Rate;
    protected $TaxRate;
    protected $ClassRef_ListID;
    protected $ClassRef_FullName;
    protected $Amount;
    protected $InventorySiteRef_ListID;
    protected $InventorySiteRef_FullName;
    protected $InventorySiteLocationRef_ListID;
    protected $InventorySiteLocationRef_FullName;
    protected $SerialNumber;
    protected $LotNumber;
    protected $ServiceDate;
    protected $SalesTaxCodeRef_ListID;
    protected $SalesTaxCodeRef_FullName;
    protected $Other1;
    protected $Other2;
    protected $LinkedTxnID;
    protected $LinkedTxnLineID;
    protected $CustomField1;
    protected $CustomField2;
    protected $CustomField3;
    protected $CustomField4;
    protected $CustomField5;
    protected $CustomField6;
    protected $CustomField7;
    protected $CustomField8;
    protected $CustomField9;
    protected $CustomField10;
    protected $CustomField11;
    protected $CustomField12;
    protected $CustomField13;
    protected $CustomField14;
    protected $CustomField15;
    protected $IDKEY;
    protected $GroupIDKEY;

    public function onConstruct() {
        
        $fecha = date('Y-m-d H:m:s');
        $this->TxnLineID = ' ';
        $this->ItemRef_ListID = ' ';
        $this->ItemRef_FullName = ' ';
        $this->Description = ' ';
        $this->Quantity = ' ';
        $this->UnitOfMeasure = ' ';
        $this->OverrideUOMSetRef_ListID = ' ';
        $this->OverrideUOMSetRef_FullName = ' ';
        $this->Rate = ' ';
        $this->TaxRate = ' ';
        $this->ClassRef_ListID = ' ';
        $this->ClassRef_FullName = ' ';
        $this->Amount = ' ';
        $this->InventorySiteRef_ListID = ' ';
        $this->InventorySiteRef_FullName = ' ';
        $this->InventorySiteLocationRef_ListID = ' ';
        $this->InventorySiteLocationRef_FullName = ' ';
        $this->SerialNumber = ' ';
        $this->LotNumber = ' ';
        $this->ServiceDate = $fecha;
        $this->SalesTaxCodeRef_ListID = ' ';
        $this->SalesTaxCodeRef_FullName = ' ';
        $this->Other1 = ' ';
        $this->Other2 = ' ';
        $this->LinkedTxnID = ' ';
        $this->LinkedTxnLineID = ' ';
        $this->CustomField1 = ' ';
        $this->CustomField2 = ' ';
        $this->CustomField3 = ' ';
        $this->CustomField4 = ' ';
        $this->CustomField5 = ' ';
        $this->CustomField6 = ' ';
        $this->CustomField7 = ' ';
        $this->CustomField8 = ' ';
        $this->CustomField9 = ' ';
        $this->CustomField10 = ' ';
        $this->CustomField11 = ' ';
        $this->CustomField12 = ' ';
        $this->CustomField13 = ' ';
        $this->CustomField14 = ' ';
        $this->CustomField15 = ' ';
        $this->IDKEY = ' ';
        $this->GroupIDKEY = ' ';
    }

    /**
     * Method to set the value of field TxnLineID
     *
     * @param string $TxnLineID
     * @return $this
     */
    public function setTxnLineID($TxnLineID) {
        $this->TxnLineID = $TxnLineID;

        return $this;
    }

    /**
     * Method to set the value of field ItemRef_ListID
     *
     * @param string $ItemRef_ListID
     * @return $this
     */
    public function setItemRefListID($ItemRef_ListID) {
        $this->ItemRef_ListID = $ItemRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field ItemRef_FullName
     *
     * @param string $ItemRef_FullName
     * @return $this
     */
    public function setItemRefFullName($ItemRef_FullName) {
        $this->ItemRef_FullName = $ItemRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field Description
     *
     * @param string $Description
     * @return $this
     */
    public function setDescription($Description) {
        $this->Description = $Description;

        return $this;
    }

    /**
     * Method to set the value of field Quantity
     *
     * @param string $Quantity
     * @return $this
     */
    public function setQuantity($Quantity) {
        $this->Quantity = $Quantity;

        return $this;
    }

    /**
     * Method to set the value of field UnitOfMeasure
     *
     * @param string $UnitOfMeasure
     * @return $this
     */
    public function setUnitOfMeasure($UnitOfMeasure) {
        $this->UnitOfMeasure = $UnitOfMeasure;

        return $this;
    }

    /**
     * Method to set the value of field OverrideUOMSetRef_ListID
     *
     * @param string $OverrideUOMSetRef_ListID
     * @return $this
     */
    public function setOverrideUOMSetRefListID($OverrideUOMSetRef_ListID) {
        $this->OverrideUOMSetRef_ListID = $OverrideUOMSetRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field OverrideUOMSetRef_FullName
     *
     * @param string $OverrideUOMSetRef_FullName
     * @return $this
     */
    public function setOverrideUOMSetRefFullName($OverrideUOMSetRef_FullName) {
        $this->OverrideUOMSetRef_FullName = $OverrideUOMSetRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field Rate
     *
     * @param string $Rate
     * @return $this
     */
    public function setRate($Rate) {
        $this->Rate = $Rate;

        return $this;
    }

    /**
     * Method to set the value of field TaxRate
     *
     * @param string $TaxRate
     * @return $this
     */
    public function setTaxRate($TaxRate) {
        $this->TaxRate = $TaxRate;

        return $this;
    }

    /**
     * Method to set the value of field ClassRef_ListID
     *
     * @param string $ClassRef_ListID
     * @return $this
     */
    public function setClassRefListID($ClassRef_ListID) {
        $this->ClassRef_ListID = $ClassRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field ClassRef_FullName
     *
     * @param string $ClassRef_FullName
     * @return $this
     */
    public function setClassRefFullName($ClassRef_FullName) {
        $this->ClassRef_FullName = $ClassRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field Amount
     *
     * @param double $Amount
     * @return $this
     */
    public function setAmount($Amount) {
        $this->Amount = $Amount;

        return $this;
    }

    /**
     * Method to set the value of field InventorySiteRef_ListID
     *
     * @param string $InventorySiteRef_ListID
     * @return $this
     */
    public function setInventorySiteRefListID($InventorySiteRef_ListID) {
        $this->InventorySiteRef_ListID = $InventorySiteRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field InventorySiteRef_FullName
     *
     * @param string $InventorySiteRef_FullName
     * @return $this
     */
    public function setInventorySiteRefFullName($InventorySiteRef_FullName) {
        $this->InventorySiteRef_FullName = $InventorySiteRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field InventorySiteLocationRef_ListID
     *
     * @param string $InventorySiteLocationRef_ListID
     * @return $this
     */
    public function setInventorySiteLocationRefListID($InventorySiteLocationRef_ListID) {
        $this->InventorySiteLocationRef_ListID = $InventorySiteLocationRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field InventorySiteLocationRef_FullName
     *
     * @param string $InventorySiteLocationRef_FullName
     * @return $this
     */
    public function setInventorySiteLocationRefFullName($InventorySiteLocationRef_FullName) {
        $this->InventorySiteLocationRef_FullName = $InventorySiteLocationRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field SerialNumber
     *
     * @param string $SerialNumber
     * @return $this
     */
    public function setSerialNumber($SerialNumber) {
        $this->SerialNumber = $SerialNumber;

        return $this;
    }

    /**
     * Method to set the value of field LotNumber
     *
     * @param string $LotNumber
     * @return $this
     */
    public function setLotNumber($LotNumber) {
        $this->LotNumber = $LotNumber;

        return $this;
    }

    /**
     * Method to set the value of field ServiceDate
     *
     * @param string $ServiceDate
     * @return $this
     */
    public function setServiceDate($ServiceDate) {
        $this->ServiceDate = $ServiceDate;

        return $this;
    }

    /**
     * Method to set the value of field SalesTaxCodeRef_ListID
     *
     * @param string $SalesTaxCodeRef_ListID
     * @return $this
     */
    public function setSalesTaxCodeRefListID($SalesTaxCodeRef_ListID) {
        $this->SalesTaxCodeRef_ListID = $SalesTaxCodeRef_ListID;

        return $this;
    }

    /**
     * Method to set the value of field SalesTaxCodeRef_FullName
     *
     * @param string $SalesTaxCodeRef_FullName
     * @return $this
     */
    public function setSalesTaxCodeRefFullName($SalesTaxCodeRef_FullName) {
        $this->SalesTaxCodeRef_FullName = $SalesTaxCodeRef_FullName;

        return $this;
    }

    /**
     * Method to set the value of field Other1
     *
     * @param string $Other1
     * @return $this
     */
    public function setOther1($Other1) {
        $this->Other1 = $Other1;

        return $this;
    }

    /**
     * Method to set the value of field Other2
     *
     * @param string $Other2
     * @return $this
     */
    public function setOther2($Other2) {
        $this->Other2 = $Other2;

        return $this;
    }

    /**
     * Method to set the value of field LinkedTxnID
     *
     * @param string $LinkedTxnID
     * @return $this
     */
    public function setLinkedTxnID($LinkedTxnID) {
        $this->LinkedTxnID = $LinkedTxnID;

        return $this;
    }

    /**
     * Method to set the value of field LinkedTxnLineID
     *
     * @param string $LinkedTxnLineID
     * @return $this
     */
    public function setLinkedTxnLineID($LinkedTxnLineID) {
        $this->LinkedTxnLineID = $LinkedTxnLineID;

        return $this;
    }

    /**
     * Method to set the value of field CustomField1
     *
     * @param string $CustomField1
     * @return $this
     */
    public function setCustomField1($CustomField1) {
        $this->CustomField1 = $CustomField1;

        return $this;
    }

    /**
     * Method to set the value of field CustomField2
     *
     * @param string $CustomField2
     * @return $this
     */
    public function setCustomField2($CustomField2) {
        $this->CustomField2 = $CustomField2;

        return $this;
    }

    /**
     * Method to set the value of field CustomField3
     *
     * @param string $CustomField3
     * @return $this
     */
    public function setCustomField3($CustomField3) {
        $this->CustomField3 = $CustomField3;

        return $this;
    }

    /**
     * Method to set the value of field CustomField4
     *
     * @param string $CustomField4
     * @return $this
     */
    public function setCustomField4($CustomField4) {
        $this->CustomField4 = $CustomField4;

        return $this;
    }

    /**
     * Method to set the value of field CustomField5
     *
     * @param string $CustomField5
     * @return $this
     */
    public function setCustomField5($CustomField5) {
        $this->CustomField5 = $CustomField5;

        return $this;
    }

    /**
     * Method to set the value of field CustomField6
     *
     * @param string $CustomField6
     * @return $this
     */
    public function setCustomField6($CustomField6) {
        $this->CustomField6 = $CustomField6;

        return $this;
    }

    /**
     * Method to set the value of field CustomField7
     *
     * @param string $CustomField7
     * @return $this
     */
    public function setCustomField7($CustomField7) {
        $this->CustomField7 = $CustomField7;

        return $this;
    }

    /**
     * Method to set the value of field CustomField8
     *
     * @param string $CustomField8
     * @return $this
     */
    public function setCustomField8($CustomField8) {
        $this->CustomField8 = $CustomField8;

        return $this;
    }

    /**
     * Method to set the value of field CustomField9
     *
     * @param string $CustomField9
     * @return $this
     */
    public function setCustomField9($CustomField9) {
        $this->CustomField9 = $CustomField9;

        return $this;
    }

    /**
     * Method to set the value of field CustomField10
     *
     * @param string $CustomField10
     * @return $this
     */
    public function setCustomField10($CustomField10) {
        $this->CustomField10 = $CustomField10;

        return $this;
    }

    /**
     * Method to set the value of field CustomField11
     *
     * @param string $CustomField11
     * @return $this
     */
    public function setCustomField11($CustomField11) {
        $this->CustomField11 = $CustomField11;

        return $this;
    }

    /**
     * Method to set the value of field CustomField12
     *
     * @param string $CustomField12
     * @return $this
     */
    public function setCustomField12($CustomField12) {
        $this->CustomField12 = $CustomField12;

        return $this;
    }

    /**
     * Method to set the value of field CustomField13
     *
     * @param string $CustomField13
     * @return $this
     */
    public function setCustomField13($CustomField13) {
        $this->CustomField13 = $CustomField13;

        return $this;
    }

    /**
     * Method to set the value of field CustomField14
     *
     * @param string $CustomField14
     * @return $this
     */
    public function setCustomField14($CustomField14) {
        $this->CustomField14 = $CustomField14;

        return $this;
    }

    /**
     * Method to set the value of field CustomField15
     *
     * @param string $CustomField15
     * @return $this
     */
    public function setCustomField15($CustomField15) {
        $this->CustomField15 = $CustomField15;

        return $this;
    }

    /**
     * Method to set the value of field IDKEY
     *
     * @param string $IDKEY
     * @return $this
     */
    public function setIDKEY($IDKEY) {
        $this->IDKEY = $IDKEY;

        return $this;
    }

    /**
     * Method to set the value of field GroupIDKEY
     *
     * @param string $GroupIDKEY
     * @return $this
     */
    public function setGroupIDKEY($GroupIDKEY) {
        $this->GroupIDKEY = $GroupIDKEY;

        return $this;
    }

    /**
     * Returns the value of field TxnLineID
     *
     * @return string
     */
    public function getTxnLineID() {
        return $this->TxnLineID;
    }

    /**
     * Returns the value of field ItemRef_ListID
     *
     * @return string
     */
    public function getItemRefListID() {
        return $this->ItemRef_ListID;
    }

    /**
     * Returns the value of field ItemRef_FullName
     *
     * @return string
     */
    public function getItemRefFullName() {
        return $this->ItemRef_FullName;
    }

    /**
     * Returns the value of field Description
     *
     * @return string
     */
    public function getDescription() {
        return $this->Description;
    }

    /**
     * Returns the value of field Quantity
     *
     * @return string
     */
    public function getQuantity() {
        return $this->Quantity;
    }

    /**
     * Returns the value of field UnitOfMeasure
     *
     * @return string
     */
    public function getUnitOfMeasure() {
        return $this->UnitOfMeasure;
    }

    /**
     * Returns the value of field OverrideUOMSetRef_ListID
     *
     * @return string
     */
    public function getOverrideUOMSetRefListID() {
        return $this->OverrideUOMSetRef_ListID;
    }

    /**
     * Returns the value of field OverrideUOMSetRef_FullName
     *
     * @return string
     */
    public function getOverrideUOMSetRefFullName() {
        return $this->OverrideUOMSetRef_FullName;
    }

    /**
     * Returns the value of field Rate
     *
     * @return string
     */
    public function getRate() {
        return $this->Rate;
    }

    /**
     * Returns the value of field TaxRate
     *
     * @return string
     */
    public function getTaxRate() {
        return $this->TaxRate;
    }

    /**
     * Returns the value of field ClassRef_ListID
     *
     * @return string
     */
    public function getClassRefListID() {
        return $this->ClassRef_ListID;
    }

    /**
     * Returns the value of field ClassRef_FullName
     *
     * @return string
     */
    public function getClassRefFullName() {
        return $this->ClassRef_FullName;
    }

    /**
     * Returns the value of field Amount
     *
     * @return double
     */
    public function getAmount() {
        return $this->Amount;
    }

    /**
     * Returns the value of field InventorySiteRef_ListID
     *
     * @return string
     */
    public function getInventorySiteRefListID() {
        return $this->InventorySiteRef_ListID;
    }

    /**
     * Returns the value of field InventorySiteRef_FullName
     *
     * @return string
     */
    public function getInventorySiteRefFullName() {
        return $this->InventorySiteRef_FullName;
    }

    /**
     * Returns the value of field InventorySiteLocationRef_ListID
     *
     * @return string
     */
    public function getInventorySiteLocationRefListID() {
        return $this->InventorySiteLocationRef_ListID;
    }

    /**
     * Returns the value of field InventorySiteLocationRef_FullName
     *
     * @return string
     */
    public function getInventorySiteLocationRefFullName() {
        return $this->InventorySiteLocationRef_FullName;
    }

    /**
     * Returns the value of field SerialNumber
     *
     * @return string
     */
    public function getSerialNumber() {
        return $this->SerialNumber;
    }

    /**
     * Returns the value of field LotNumber
     *
     * @return string
     */
    public function getLotNumber() {
        return $this->LotNumber;
    }

    /**
     * Returns the value of field ServiceDate
     *
     * @return string
     */
    public function getServiceDate() {
        return $this->ServiceDate;
    }

    /**
     * Returns the value of field SalesTaxCodeRef_ListID
     *
     * @return string
     */
    public function getSalesTaxCodeRefListID() {
        return $this->SalesTaxCodeRef_ListID;
    }

    /**
     * Returns the value of field SalesTaxCodeRef_FullName
     *
     * @return string
     */
    public function getSalesTaxCodeRefFullName() {
        return $this->SalesTaxCodeRef_FullName;
    }

    /**
     * Returns the value of field Other1
     *
     * @return string
     */
    public function getOther1() {
        return $this->Other1;
    }

    /**
     * Returns the value of field Other2
     *
     * @return string
     */
    public function getOther2() {
        return $this->Other2;
    }

    /**
     * Returns the value of field LinkedTxnID
     *
     * @return string
     */
    public function getLinkedTxnID() {
        return $this->LinkedTxnID;
    }

    /**
     * Returns the value of field LinkedTxnLineID
     *
     * @return string
     */
    public function getLinkedTxnLineID() {
        return $this->LinkedTxnLineID;
    }

    /**
     * Returns the value of field CustomField1
     *
     * @return string
     */
    public function getCustomField1() {
        return $this->CustomField1;
    }

    /**
     * Returns the value of field CustomField2
     *
     * @return string
     */
    public function getCustomField2() {
        return $this->CustomField2;
    }

    /**
     * Returns the value of field CustomField3
     *
     * @return string
     */
    public function getCustomField3() {
        return $this->CustomField3;
    }

    /**
     * Returns the value of field CustomField4
     *
     * @return string
     */
    public function getCustomField4() {
        return $this->CustomField4;
    }

    /**
     * Returns the value of field CustomField5
     *
     * @return string
     */
    public function getCustomField5() {
        return $this->CustomField5;
    }

    /**
     * Returns the value of field CustomField6
     *
     * @return string
     */
    public function getCustomField6() {
        return $this->CustomField6;
    }

    /**
     * Returns the value of field CustomField7
     *
     * @return string
     */
    public function getCustomField7() {
        return $this->CustomField7;
    }

    /**
     * Returns the value of field CustomField8
     *
     * @return string
     */
    public function getCustomField8() {
        return $this->CustomField8;
    }

    /**
     * Returns the value of field CustomField9
     *
     * @return string
     */
    public function getCustomField9() {
        return $this->CustomField9;
    }

    /**
     * Returns the value of field CustomField10
     *
     * @return string
     */
    public function getCustomField10() {
        return $this->CustomField10;
    }

    /**
     * Returns the value of field CustomField11
     *
     * @return string
     */
    public function getCustomField11() {
        return $this->CustomField11;
    }

    /**
     * Returns the value of field CustomField12
     *
     * @return string
     */
    public function getCustomField12() {
        return $this->CustomField12;
    }

    /**
     * Returns the value of field CustomField13
     *
     * @return string
     */
    public function getCustomField13() {
        return $this->CustomField13;
    }

    /**
     * Returns the value of field CustomField14
     *
     * @return string
     */
    public function getCustomField14() {
        return $this->CustomField14;
    }

    /**
     * Returns the value of field CustomField15
     *
     * @return string
     */
    public function getCustomField15() {
        return $this->CustomField15;
    }

    /**
     * Returns the value of field IDKEY
     *
     * @return string
     */
    public function getIDKEY() {
        return $this->IDKEY;
    }

    /**
     * Returns the value of field GroupIDKEY
     *
     * @return string
     */
    public function getGroupIDKEY() {
        return $this->GroupIDKEY;
    }

    /**
     * Initialize method for model.
     */
    public function initialize() {
        $this->setSchema("mecanica");
        $this->belongsTo(
                'IDKEY', 'Invoice', 'TxnID');
        $this->belongsTo(
                'ItemRef_ListID', 'Items', 'quickbooks_listid');
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource() {
        return 'invoicelinedetail';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Invoicelinedetail[]|Invoicelinedetail
     */
    public static function find($parameters = null) {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Invoicelinedetail
     */
    public static function findFirst($parameters = null) {
        return parent::findFirst($parameters);
    }

}
